/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/pages/LightShading/assets/suzanne.glb 
*/

import { useGLTF } from "@react-three/drei";
import suzanne from "./suzanne.glb?url";
import * as THREE from "three";
import { PropsWithChildren, RefObject } from "react";

type SuzanneModelProps = {
  ref: RefObject<THREE.Group>;
};

export default function SuzanneModel(
  props: PropsWithChildren<SuzanneModelProps>
) {
  const { nodes } = useGLTF(suzanne);
  const suzanneNode = nodes.Suzanne as THREE.Mesh;
  return (
    <group {...props} dispose={null} ref={props.ref}>
      <mesh geometry={suzanneNode.geometry}>{props.children}</mesh>
    </group>
  );
}

useGLTF.preload(suzanne);
