/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {
  useMemo,
  useContext,
  createContext,
  PropsWithChildren,
} from "react";
import {
  useGLTF,
  Merged,
  MergedProps,
  InstanceProps,
  useTexture,
} from "@react-three/drei";
import corneModel from "../../assets/corne.glb?url";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { ThreeElements } from "@react-three/fiber";
import leftScreen from "../../assets/corne_screen_left.png";
import rightScreen from "../../assets/corne_screen_right.png";

type GLTFResult = GLTF & {
  nodes: {
    display: THREE.Mesh;
    display_1: THREE.Mesh;
    case: THREE.Mesh;
    screen: THREE.Mesh;
    escape: THREE.Mesh;
    b: THREE.Mesh;
    l: THREE.Mesh;
    d: THREE.Mesh;
    c: THREE.Mesh;
    v: THREE.Mesh;
    tab: THREE.Mesh;
    n: THREE.Mesh;
    r: THREE.Mesh;
    t: THREE.Mesh;
    s: THREE.Mesh;
    g: THREE.Mesh;
    modifier001: THREE.Mesh;
    x: THREE.Mesh;
    q: THREE.Mesh;
    m: THREE.Mesh;
    w: THREE.Mesh;
    z: THREE.Mesh;
    switch_1: THREE.Mesh;
    switch_2: THREE.Mesh;
    switch_3: THREE.Mesh;
    space: THREE.Mesh;
    modifier003: THREE.Mesh;
    modifier002: THREE.Mesh;
  };
  materials: {
    screen: THREE.MeshPhysicalMaterial;
    pcb: THREE.MeshStandardMaterial;
    metal: THREE.MeshStandardMaterial;
    keycap_stem: THREE.MeshStandardMaterial;
    keycap_base: THREE.MeshStandardMaterial;
    base_keycap: THREE.MeshStandardMaterial;
    fuji_keycap: THREE.MeshStandardMaterial;
    modifiers_keycap: THREE.MeshStandardMaterial;
  };
};
type CorneContext = {
  Switch: React.FC<InstanceProps>;
  Switch1: React.FC<InstanceProps>;
  Switch2: React.FC<InstanceProps>;
  BaseKey: React.FC<InstanceProps>;
  Modifier: React.FC<InstanceProps>;
};

const context = createContext<CorneContext | null>(null);
export function CorneInstances({
  children,
  ...props
}: PropsWithChildren<Omit<MergedProps, "children" | "meshes">>) {
  const { nodes } = useGLTF(corneModel);
  const instances = useMemo(
    () => ({
      Switch: nodes.switch_1,
      Switch1: nodes.switch_2,
      Switch2: nodes.switch_3,
      BaseKey: nodes.b,
      Modifier: nodes.tab,
    }),
    [nodes],
  );
  return (
    <Merged {...props} meshes={instances}>
      {(instances) => (
        <context.Provider value={instances as unknown as CorneContext}>
          {children}
        </context.Provider>
      )}
    </Merged>
  );
}

export default function Model({
  flip,
  ...props
}: ThreeElements["group"] & { flip?: boolean }) {
  const instances = useContext(context);
  const { nodes, materials } = useGLTF(corneModel) as unknown as GLTFResult;

  const leftScreenTexture = useTexture(leftScreen);
  leftScreenTexture.flipY = false;

  const rightScreenTexture = useTexture(rightScreen);
  rightScreenTexture.flipY = false;

  if (!instances) {
    throw new Error("CorneInstances not found");
  }

  const rotation = (Math.PI / 16) * (flip ? -1 : 1);
  const position = 1.65 * (flip ? 1 : -1);
  const texture = flip ? rightScreenTexture : leftScreenTexture;
  return (
    <group
      {...props}
      dispose={null}
      scale={flip ? [-20, 20, 20] : [20, 20, 20]}
      rotation={[0, rotation, 0]}
      position={[position, 0, 0]}
    >
      <group name="nice_nano" position={[0.054, 0.013, -0.012]}>
        <mesh
          name="display"
          castShadow
          receiveShadow
          geometry={nodes.display.geometry}
        >
          <meshStandardMaterial map={texture} />
        </mesh>
        <mesh
          name="display_1"
          castShadow
          receiveShadow
          geometry={nodes.display_1.geometry}
        >
          <meshStandardMaterial map={texture} />
        </mesh>
      </group>
      <mesh
        name="case"
        castShadow
        receiveShadow
        geometry={nodes["case"].geometry}
        material={materials.metal}
        position={[0.049, 0.011, 0.013]}
      />
      <mesh
        name="screen"
        castShadow
        receiveShadow
        geometry={nodes.screen.geometry}
        position={[0.054, 0.018, -0.002]}
      >
        <meshPhysicalMaterial
          transparent
          opacity={0.5}
          ior={1.492}
          roughness={0.6}
        />
      </mesh>
      <group name="switch" position={[-0.057, 0.014, -0.023]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch001" position={[-0.039, 0.014, -0.023]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <mesh
        name="escape"
        castShadow
        receiveShadow
        geometry={nodes.escape.geometry}
        material={flip ? materials.modifiers_keycap : materials.fuji_keycap}
        position={[-0.057, 0.021, -0.023]}
      />
      <instances.BaseKey name="b" position={[-0.039, 0.021, -0.023]} />
      <group name="switch002" position={[-0.022, 0.014, -0.023]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <instances.BaseKey name="l" position={[-0.022, 0.021, -0.023]} />
      <group name="switch003" position={[-0.004, 0.014, -0.023]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <instances.BaseKey name="d" position={[-0.004, 0.021, -0.023]} />
      <group name="switch004" position={[0.014, 0.014, -0.023]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <instances.BaseKey name="c" position={[0.014, 0.021, -0.023]} />
      <group name="switch005" position={[0.031, 0.014, -0.023]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <instances.BaseKey name="v" position={[0.031, 0.021, -0.023]} />
      <group name="switch006" position={[-0.057, 0.014, -0.006]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch008" position={[-0.039, 0.014, -0.006]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch009" position={[-0.022, 0.014, -0.006]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch010" position={[-0.004, 0.014, -0.006]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch011" position={[0.014, 0.014, -0.006]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch012" position={[0.031, 0.014, -0.006]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <instances.Modifier name="tab" position={[-0.057, 0.021, -0.006]} />
      <instances.BaseKey name="n" position={[-0.039, 0.021, -0.006]} />
      <instances.BaseKey name="r" position={[-0.022, 0.021, -0.006]} />
      <instances.BaseKey name="t" position={[-0.004, 0.021, -0.006]} />
      <instances.BaseKey name="s" position={[0.014, 0.021, -0.006]} />
      <instances.BaseKey name="g" position={[0.031, 0.021, -0.006]} />
      <group name="switch013" position={[-0.039, 0.014, 0.012]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch014" position={[-0.022, 0.014, 0.012]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch014" position={[-0.004, 0.014, 0.012]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch016" position={[0.014, 0.014, 0.012]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch017" position={[0.031, 0.014, 0.012]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch007" position={[-0.057, 0.014, 0.012]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <instances.Modifier
        name="modifier001"
        position={[-0.057, 0.021, 0.012]}
      />
      <instances.BaseKey name="x" position={[-0.039, 0.021, 0.012]} />
      <instances.BaseKey name="q" position={[-0.022, 0.021, 0.012]} />
      <instances.BaseKey name="m" position={[-0.004, 0.021, 0.012]} />
      <instances.BaseKey name="w" position={[0.014, 0.021, 0.012]} />
      <instances.BaseKey name="z" position={[0.031, 0.021, 0.012]} />
      <group
        name="switch020"
        position={[0.049, 0.014, 0.034]}
        rotation={[0, -0.638, 0]}
      >
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group
        name="switch018"
        position={[0.028, 0.014, 0.031]}
        rotation={[0, -0.202, 0]}
      >
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <group name="switch019" position={[0.009, 0.014, 0.029]}>
        <instances.Switch name="switch_1" />
        <instances.Switch1 name="switch_2" />
        <instances.Switch2 name="switch_3" />
      </group>
      <mesh
        name="space"
        castShadow
        receiveShadow
        geometry={nodes.space.geometry}
        material={materials.base_keycap}
        position={[0.049, 0.021, 0.034]}
        rotation={[0, -0.633, 0]}
        scale={[3.267, 1.943, 2.482]}
      />
      <instances.Modifier
        name="modifier003"
        position={[0.028, 0.021, 0.031]}
        rotation={[0, -0.202, 0]}
      />
      <instances.Modifier name="modifier002" position={[0.009, 0.021, 0.029]} />
    </group>
  );
}

useGLTF.preload(corneModel);
