/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/pages/LightShading/assets/suzanne.glb 
*/

import { useGLTF } from "@react-three/drei";
import suzanne from "./assets/suzanne.glb?url";
import * as THREE from "three";
import { GroupProps } from "@react-three/fiber";
import { forwardRef, PropsWithChildren } from "react";

const SuzanneModel = forwardRef<THREE.Group, PropsWithChildren<GroupProps>>(
  (props, ref) => {
    const { nodes } = useGLTF(suzanne);
    const suzanneNode = nodes.Suzanne as THREE.Mesh;
    return (
      <group {...props} dispose={null} ref={ref}>
        <mesh geometry={suzanneNode.geometry}>{props.children}</mesh>
      </group>
    );
  }
);

export default SuzanneModel;

useGLTF.preload(suzanne);
